basePath: /
definitions:
  helper.JsonObject:
    properties:
      code:
        description: '* 状态码'
        type: string
      content:
        description: '* 内容体'
        type: object
      message:
        description: '* 消息'
        type: string
    type: object
  helper.PageBean:
    properties:
      page:
        description: '* 当前页'
        type: integer
      pageSize:
        description: '* 每页显示的最大行数'
        type: integer
      rows:
        description: '* 每行的数据'
        type: object
      total:
        description: '* 总记录数'
        type: integer
    type: object
host: 192.168.0.103:8080
info:
  contact:
    email: yongtao.yin@bsit.cn
    name: YinYongTao
    url: https://github.com/YinYongTao/gin-first
  description: 这是一个 gin 框架应用 swagger 的示例
  license: {}
  title: gin-first API 文档
  version: "1.0"
paths:
  /api/delete_user:
    post:
      consumes:
      - application/json
      description: 删除用户信息
      parameters:
      - description: 用户记录id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.JsonObject'
            type: object
      summary: 用户信息删除接口
      tags:
      - UserController
  /api/get_all_users:
    get:
      consumes:
      - application/json
      description: 获取所有用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.JsonObject'
            type: object
      summary: 获取所有用户接口
      tags:
      - UserController
  /api/get_user_page:
    get:
      consumes:
      - application/json
      description: 用户信息分页查询
      parameters:
      - description: 页码
        in: query
        name: page
        required: true
        type: string
      - description: 每页显示最大行
        in: query
        name: page_size
        required: true
        type: string
      - description: 用户名
        in: query
        name: username
        type: string
      - description: 电话
        in: query
        name: phone
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.PageBean'
            type: object
      summary: 用户信息分页查询接口
      tags:
      - UserController
  /login:
    post:
      consumes:
      - application/json
      description: 处理系统用户登陆
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.JsonObject'
            type: object
      summary: 用户登陆接口
      tags:
      - LoginController
swagger: "2.0"
