server:
  addr: 0.0.0.0:8080
  read-timeout: 10
  write-timeout: 10
  idle-timeout: 300
  max-header-bytes: 10485760

gin:
  #运行模式 "debug", "release" , "test"
  run-mode: debug
  #是否开启请求方式检测
  handle-method-not-allowed: true
  #设置请求占用最大空间 10mb
  max-multipart-memory: 10485760
