// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-11-05 23:53:26.516755045 +0800 CST m=+0.038334149

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "这是一个 gin 框架应用 swagger 的示例",
        "title": "gin-first API 文档",
        "contact": {
            "name": "YinYongTao",
            "url": "https://github.com/YinYongTao/gin-first",
            "email": "yongtao.yin@bsit.cn"
        },
        "license": {},
        "version": "1.0"
    },
    "host": "192.168.0.103:8080",
    "basePath": "/",
    "paths": {
        "/api/delete_user": {
            "post": {
                "description": "删除用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserController"
                ],
                "summary": "用户信息删除接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户记录id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helper.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/get_all_users": {
            "get": {
                "description": "获取所有用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserController"
                ],
                "summary": "获取所有用户接口",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helper.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/get_user_page": {
            "get": {
                "description": "用户信息分页查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserController"
                ],
                "summary": "用户信息分页查询接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页显示最大行",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "电话",
                        "name": "phone",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helper.PageBean"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "处理系统用户登陆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LoginController"
                ],
                "summary": "用户登陆接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helper.JsonObject"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helper.JsonObject": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "* 状态码",
                    "type": "string"
                },
                "content": {
                    "description": "* 内容体",
                    "type": "object"
                },
                "message": {
                    "description": "* 消息",
                    "type": "string"
                }
            }
        },
        "helper.PageBean": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "* 当前页",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "* 每页显示的最大行数",
                    "type": "integer"
                },
                "rows": {
                    "description": "* 每行的数据",
                    "type": "object"
                },
                "total": {
                    "description": "* 总记录数",
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
