// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-11-06 14:42:19.084185798 +0800 CST m=+0.085091901

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "这是一个 gin 框架应用 swagger 的示例",
        "title": "gin-first API 文档",
        "contact": {
            "name": "YinYongTao",
            "url": "https://github.com/YinYongTao/gin-first",
            "email": "yongtao.yin@bsit.cn"
        },
        "license": {},
        "version": "2.0"
    },
    "host": "0.0.0.0:8080",
    "basePath": "/",
    "paths": {
        "/api/delete_user": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserController"
                ],
                "summary": "删除用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户记录id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helper.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/get_all_users": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserController"
                ],
                "summary": "获取所有用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helper.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/get_user": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserController"
                ],
                "summary": "用户信息回显",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户记录id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.User"
                        }
                    }
                }
            }
        },
        "/api/get_user_page": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserController"
                ],
                "summary": "用户信息分页查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页显示最大行",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "电话",
                        "name": "phone",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helper.PageBean"
                        }
                    }
                }
            }
        },
        "/api/save_role": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoleController"
                ],
                "summary": "添加修改角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色id,新增时id为空",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "角色名称",
                        "name": "role_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "角色类别标识",
                        "name": "role_key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "角色描述信息",
                        "name": "description",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helper.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/save_user": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserController"
                ],
                "summary": "添加、修改用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户记录id,新增时id为空",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "电话号码",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "邮件",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商户号",
                        "name": "merchant_no",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "角色id",
                        "name": "role_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helper.JsonObject"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LoginController"
                ],
                "summary": "用户登陆接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helper.JsonObject"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helper.JsonObject": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "* 状态码",
                    "type": "string"
                },
                "content": {
                    "description": "* 内容体",
                    "type": "object"
                },
                "message": {
                    "description": "* 消息",
                    "type": "string"
                }
            }
        },
        "helper.PageBean": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "* 当前页",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "* 每页显示的最大行数",
                    "type": "integer"
                },
                "rows": {
                    "description": "* 每行的数据",
                    "type": "object"
                },
                "total": {
                    "description": "* 总记录数",
                    "type": "integer"
                }
            }
        },
        "model.Role": {
            "type": "object",
            "required": [
                "roleName",
                "roleKey"
            ],
            "properties": {
                "createdAt": {
                    "description": "* 创建时间",
                    "type": "string"
                },
                "deletedAt": {
                    "description": "* 删除时间",
                    "type": "string"
                },
                "description": {
                    "description": "* 角色描述",
                    "type": "string"
                },
                "id": {
                    "description": "* 主键id",
                    "type": "string"
                },
                "roleKey": {
                    "description": "* 角色类别标识",
                    "type": "string"
                },
                "roleName": {
                    "description": "* 角色名称",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "* 更新时间",
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "required": [
                "userName",
                "phone"
            ],
            "properties": {
                "createdAt": {
                    "description": "* 创建时间",
                    "type": "string"
                },
                "deletedAt": {
                    "description": "* 删除时间",
                    "type": "string"
                },
                "email": {
                    "description": "* 邮件",
                    "type": "string"
                },
                "flag": {
                    "description": "* 标志 1 表示这个账号是由管理方为商户添加的账号",
                    "type": "integer"
                },
                "id": {
                    "description": "* 主键",
                    "type": "string"
                },
                "loginTime": {
                    "description": "* 最后一次登陆时间",
                    "type": "string"
                },
                "logonCount": {
                    "description": "* 登陆次数",
                    "type": "integer"
                },
                "merchantName": {
                    "description": "* 商户名称",
                    "type": "string"
                },
                "merchantNo": {
                    "description": "* 商户号",
                    "type": "string"
                },
                "phone": {
                    "description": "* 电话",
                    "type": "string"
                },
                "role": {
                    "description": "* 用户对应的角色",
                    "type": "object",
                    "$ref": "#/definitions/model.Role"
                },
                "roleId": {
                    "description": "* 外键",
                    "type": "string"
                },
                "status": {
                    "description": "* 状态  0 正常",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "* 更新时间",
                    "type": "string"
                },
                "userName": {
                    "description": "* 姓名",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
